// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbvjypmjldzyqjjhclrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFidmp5cG1qbGR6eXFqamhjbHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTcyNzcsImV4cCI6MjA3MjUzMzI3N30.zUUCFX7tnr190-egH5D6szLz_Uxkc7nxGB1dW1imTbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});